2019-01-25 16:31:43,457 ERROR    Exception occured in gene 0, ref mode, sample test1pos 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 16:31:43,550 ERROR    Exception occured in gene 0, germline mode, sample test1pos 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 16:31:43,729 ERROR    Exception occured in gene 0, somatic mode, sample test1pos 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 16:31:43,897 ERROR    Exception occured in gene 0, somatic_and_germline mode, sample test1pos 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 16:31:43,994 ERROR    Exception occured in gene 0, ref mode, sample test1neg 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 16:31:44,089 ERROR    Exception occured in gene 0, germline mode, sample test1neg 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 16:31:44,252 ERROR    Exception occured in gene 0, somatic mode, sample test1neg 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 16:31:44,421 ERROR    Exception occured in gene 0, somatic_and_germline mode, sample test1neg 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 16:42:56,819 ERROR    Exception occured in gene 0, ref mode, sample test1pos 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 16:42:56,984 ERROR    Exception occured in gene 0, germline mode, sample test1pos 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 16:42:57,308 ERROR    Exception occured in gene 0, somatic mode, sample test1pos 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 16:42:57,626 ERROR    Exception occured in gene 0, somatic_and_germline mode, sample test1pos 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 16:42:57,803 ERROR    Exception occured in gene 0, ref mode, sample test1neg 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 16:42:57,980 ERROR    Exception occured in gene 0, germline mode, sample test1neg 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 16:42:58,326 ERROR    Exception occured in gene 0, somatic mode, sample test1neg 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 16:42:58,642 ERROR    Exception occured in gene 0, somatic_and_germline mode, sample test1neg 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 17:10:24,926 ERROR    Exception occured in gene 0, ref mode, sample test1pos 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 17:10:25,023 ERROR    Exception occured in gene 0, germline mode, sample test1pos 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 17:10:25,198 ERROR    Exception occured in gene 0, somatic mode, sample test1pos 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 17:10:25,360 ERROR    Exception occured in gene 0, somatic_and_germline mode, sample test1pos 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 17:10:25,460 ERROR    Exception occured in gene 0, ref mode, sample test1neg 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 17:10:25,547 ERROR    Exception occured in gene 0, germline mode, sample test1neg 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 17:10:25,713 ERROR    Exception occured in gene 0, somatic mode, sample test1neg 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 17:10:25,864 ERROR    Exception occured in gene 0, somatic_and_germline mode, sample test1neg 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 17:41:34,439 ERROR    Exception occured in gene 0, ref mode, sample test1pos 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 17:41:34,549 ERROR    Exception occured in gene 0, germline mode, sample test1pos 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 17:41:34,721 ERROR    Exception occured in gene 0, somatic mode, sample test1pos 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 17:41:34,877 ERROR    Exception occured in gene 0, somatic_and_germline mode, sample test1pos 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 17:41:34,989 ERROR    Exception occured in gene 0, ref mode, sample test1neg 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 17:41:35,084 ERROR    Exception occured in gene 0, germline mode, sample test1neg 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 17:41:35,251 ERROR    Exception occured in gene 0, somatic mode, sample test1neg 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
2019-01-25 17:41:35,416 ERROR    Exception occured in gene 0, somatic_and_germline mode, sample test1neg 
Traceback (most recent call last):
  File "/Users/jiayu/PycharmProjects/CBM_RA/projects2018_immunopepper/immunopepper/main_immuno.py", line 207, in main
    if len(concat_peptide_list) >0:
UnboundLocalError: local variable 'concat_peptide_list' referenced before assignment
